trigger:
- release

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: onPush
  jobs:
  - job: onPushJob

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Install dependencies'

    - checkout: self
      persistCredentials: true
      clean: true

    - script: git checkout master
      displayName: 'Get Latest Branch'    

    - script: |
        git diff --name-only --diff-filter=AMR HEAD^1 HEAD | xargs -I '{}' cp --parents -r '{}' $(Build.BinariesDirectory)

        mkdir -p $(Build.BinariesDirectory)/package/libs
        cp $(Build.Repository.LocalPath)/package/dist/*.* $(Build.BinariesDirectory)/package/libs

        mkdir -p $(Build.BinariesDirectory)/cicd-scripts
        cp $(Build.Repository.LocalPath)/cicd-scripts/*.* $(Build.BinariesDirectory)/cicd-scripts
      displayName: 'Get Changes'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: 'DatabricksBuild'